# Generated by Django 6.0.7 on 2026-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Número do telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
